name = "Easy Japanese Insdustrial"
author = "javakky"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd2575986447a6b607d47d7099fdd63155d17e232be75fd1f13f1613229012a7"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
