name = "Easy Japanese Insdustrial"
author = "javakky"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b96176d5659bed1393fabd1112073470f57479acd7c9e20c0344d414704746a5"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
