
#net.minecraft.scalar.mineall.mod_MineAllSMP
[configuration]
	#String: "iron_pickaxe, wooden_pickaxe, stone_pickaxe, diamond_pickaxe, golden_pickaxe, netherite_pickaxe, wooden_hoe,stone_hoe,golden_hoe,iron_hoe,diamond_hoe,netherite_hoe"
	itemIds = "iron_pickaxe, wooden_pickaxe, stone_pickaxe, diamond_pickaxe, golden_pickaxe, ic2:tool_pickaxe_bronze, ic2:tool_pickaxe_aluminium, ic2:drill, ic2:diamond_drill, ic2:advanced_drill, mekanismtools:wood_paxel, mekanismtools:stone_paxel, mekanismtools:iron_paxel, mekanismtools:diamond_paxel, mekanismtools:gold_paxel, mekanismtools:netherite_paxel, mekanismtools:bronze_paxel, mekanismtools:lapis_lazuli_paxel, mekanismtools:lapis_lazuli_pickaxe, mekanismtools:osmium_paxel, mekanismtools:osmium_pickaxe, mekanismtools:refined_glowstone_paxel, mekanismtools:refined_glowstone_pickaxe, mekanismtools:refined_obsidian_paxel, mekanismtools:refined_obsidian_pickaxe, mekanismtools:steel_paxel, mekanismtools:steel_pickaxe"
	#String: "gold_ore, iron_ore, coal_ore, lapis_ore, obsidian, diamond_ore, redstone_ore, glowstone, emerald_ore, nether_quartz_ore, granite, polished_granite, diorite, polished_diorite, andesite, polished_andesite,ancient_debris,nether_gold_ore,sponge,wet_sponge,nether_wart_block,warped_wart_block,crying_obsidian,ancient_debris, deepslate_coal_ore, deepslate_copper_ore, deepslate_diamond_ore, deepslate_emerald_ore, deepslate_gold_ore, deepslate_iron_ore, deepslate_lapis_ore, deepslate_redstone_ore"
	blockIds = "gold_ore, iron_ore, coal_ore, lapis_ore, diamond_ore, redstone_ore, glowstone, emerald_ore, nether_quartz_ore, nether_gold_ore, deepslate_coal_ore, deepslate_copper_ore, deepslate_diamond_ore, deepslate_emerald_ore, deepslate_gold_ore, deepslate_iron_ore, deepslate_lapis_ore, deepslate_redstone_ore, mekanism:copper_ore, mekanism:tin_ore,mekanism:osmium_ore, mekanism:uranium_ore, mekanism:fluorite_ore, mekanism:lead_ore, mekanism:deepslate_tin_ore, mekanism:deepslate_osmium_ore, mekanism:deepslate_uranium_ore, mekanism:deepslate_fluorite_ore, mekanism:deepslate_lead_ore, ic2:resource"
	#Boolean: true
	DestroyUnder = false
	#Boolean: true
	StartMode = true
	#String: "KEY_M"
	Key = "KEY_M"
	#Integer: 0
	Limiter = 0
	#Integer: 0
	#0:not decrease durability 1,2:decrease durability(1=until whole blocks 2=until break an item)
	Durability = 0
	#Boolean: false
	AutoCollect = true
	#Boolean: false
	DropGather = true
	#String: "mod_mineall"
	channelName = "mod_mineall"
	#Boolean: true
	UseOreTag = true

